### ISSUE TITLE
Please add aria2c support，

### ISSUE THREAD

**Issue by ui1840** [database64128/youtube-dl-wpf#83]
Please add aria2c support,
So that you can get a faster and more stable download speed,
thanks,

**Comment by database64128** [comment]
Sorry for the delay in replying. I have looked into implementing this feature for both `youtube-dl` and `yt-dlp`. Turns out these two have quite different mechanisms for managing external downloaders, which makes it quite challenging to make a unified interface that works well for both backends.

So instead of adding dedicated controls for external downloader support in GUI, I'm planning to add support for specifying custom command-line arguments. You can then just add the required command-line options and arguments to use an external downloader. What do you think?

**Comment by ui1840** [comment]
> 
> 
> Sorry for the delay in replying. I have looked into implementing this feature for both `youtube-dl` and `yt-dlp`. Turns out these two have quite different mechanisms for managing external downloaders, which makes it quite challenging to make a unified interface that works well for both backends.
> 
> So instead of adding dedicated controls for external downloader support in GUI, I'm planning to add support for specifying custom command-line arguments. You can then just add the required command-line options and arguments to use an external downloader. What do you think?

Thank you very much, I am looking forward to the realization of this function,

**Comment by database64128** [comment]
Implemented in c54c1aebaedfe30f6e0401a2d6ce0fb36716f06f.

You can now set custom command-line arguments. There are two scopes: global and download. Global arguments apply to both _download_ and _list formats_ operations. Download arguments only apply to download operations. All download arguments are shown as chips in the download tab.

Download the binaries from https://github.com/database64128/youtube-dl-wpf/actions/runs/1500587054.

**Comment by database64128** [comment]
As I said before, you need to specify the arguments as if they were parsed by your shell. In my previous reply, I made a mistake and forgot to drop the quotation marks. Try:

- `--downloader`
- `aria2c`
- `--downloader-args`
- `aria2c:-x 4 -k 1M --all-proxy=127.0.0.1:7890`

**Comment by database64128** [comment]
> I don't know how youtube-dl-wpf deals with these white space.

youtube-dl-wpf passes the arguments as-is without any interpretation or modification. Please stop guessing and learn the basics of how arguments are passed when spawning a process.
